//SPDX-License-Identifier: LicenseRef-PolyForm-Strict-1.0.0
pragma solidity 0.8.24;

/**
 * @dev Pool creation parameters specific to fixed pools.
 * @dev Contains the specific configuration needed to initialize a fixed pool.
 *
 * @dev **spacing0**           Height spacing for token0 positions.
 * @dev **spacing1**           Height spacing for token1 positions.
 * @dev **packedRatio**        Packed ratio of token0 to token1 representing price.
 */
struct FixedPoolCreationDetails {
    uint8 spacing0;
    uint8 spacing1;
    uint256 packedRatio;
}

/**
 * @dev State data for fixed price liquidity pools
 * @dev Contains all on-chain state for fixed pools, including reserves, fee balances, and per-side height structures.
 *
 * @dev **sqrtPriceX96**         Fixed price of the pool as sqrt(price) * 2^96.
 * @dev **packedRatio**          Packed ratio of token0 to token1 representing price.
 * @dev **position0ShareOf0**    Total token0 contributed by token0 positions.
 * @dev **position1ShareOf1**    Total token1 contributed by token1 positions.
 * @dev **height0**              Active height tracking for token0 side.
 * @dev **height1**              Active height tracking for token1 side.
 * @dev **heightMap0**           Doubly linked list of active heights for token0 side.
 * @dev **heightMap1**           Doubly linked list of active heights for token1 side.
 * @dev **heightInfo0**          Metadata for each height on token0 side.
 * @dev **heightInfo1**          Metadata for each height on token1 side.
 * @dev **dust0**                Amount of dust generated by token0 outputs.
 * @dev **dust1**                Amount of dust generated by token1 outputs.
 */
struct FixedPoolState {
    uint160 sqrtPriceX96;
    uint256 packedRatio;
    uint128 position0ShareOf0;
    uint128 position1ShareOf1;
    FixedHeightState height0;
    FixedHeightState height1;
    mapping (uint256 => FixedHeightMap) heightMap0;
    mapping (uint256 => FixedHeightMap) heightMap1;
    mapping (uint256 => FixedHeightInfo) heightInfo0;
    mapping (uint256 => FixedHeightInfo) heightInfo1;
    uint256 dust0;
    uint256 dust1;
}

/**
 * @dev View structure for fixed pool state.
 * @dev External view of fixed pool state without internal mappings for easier querying.
 *
 * @dev **sqrtPriceX96**         Current square root price in Q96 format.
 * @dev **packedRatio**          Packed ratio of token0 to token1 representing price.
 * @dev **position0ShareOf0**    Token0's share of token0 positions.
 * @dev **position1ShareOf1**    Token1's share of token1 positions.
 * @dev **currentHeight0**       Current height for token0.
 * @dev **currentHeight1**       Current height for token1.
 * @dev **consumedLiquidity0**   Consumed liquidity for token0.
 * @dev **consumedLiquidity1**   Consumed liquidity for token1.
 * @dev **liquidity0**           Available liquidity for token0.
 * @dev **liquidity1**           Available liquidity for token1.
 * @dev **remainingAtHeight0**   Remaining liquidity at current height for token0.
 * @dev **remainingAtHeight1**   Remaining liquidity at current height for token1.
 * @dev **dust0**                Amount of dust generated by token0 outputs.
 * @dev **dust1**                Amount of dust generated by token1 outputs.
 */
struct FixedPoolStateView {
    uint160 sqrtPriceX96;
    uint256 packedRatio;
    uint128 position0ShareOf0;
    uint128 position1ShareOf1;
    uint256 currentHeight0;
    uint256 currentHeight1;
    uint256 consumedLiquidity0;
    uint256 consumedLiquidity1;
    uint128 liquidity0;
    uint128 liquidity1;
    uint128 remainingAtHeight0;
    uint128 remainingAtHeight1;
    uint256 dust0;
    uint256 dust1;
}

/**
 * @dev Tracks liquidity and fee growth state across height intervals
 * @dev Used by fixed pools to represent liquidity positioning along a one-dimensional height metric.
 *
 * @dev **currentHeight**          Active height level currently being consumed.
 * @dev **consumedLiquidity**      Total liquidity consumed across all heights.
 * @dev **liquidity**              Total active liquidity at current height.
 * @dev **remainingAtHeight**      Amount of liquidity still available at current height.
 * @dev **feeGrowthGlobalOf0X128** Global fee growth in Q128 for token0 at this height.
 * @dev **feeGrowthGlobalOf1X128** Global fee growth in Q128 for token1 at this height.
 * @dev **nextHeightBelow**        Previous active height in the linked list.
 * @dev **nextHeightAbove**        Next active height in the linked list.
 */
struct FixedHeightState {
    uint256 currentHeight;
    uint256 consumedLiquidity;
    uint128 liquidity;
    uint128 remainingAtHeight;
    uint256 feeGrowthGlobalOf0X128;
    uint256 feeGrowthGlobalOf1X128;
    uint256 nextHeightBelow;
    uint256 nextHeightAbove;
}

/**
 * @dev Metadata for a specific height interval in a fixed pool
 * @dev Contains liquidity tracking and fee growth data used to manage fee distribution and state updates.
 *
 * @dev **liquidityGross**        Total liquidity referencing this height.
 * @dev **liquidityNet**          Net change in liquidity when this height is entered/exited.
 * @dev **feeGrowthOutside0X128** Accumulated fee growth outside this height for token0.
 * @dev **feeGrowthOutside1X128** Accumulated fee growth outside this height for token1.
 */
struct FixedHeightInfo {
    uint128 liquidityGross;
    int128 liquidityNet;
    uint256 feeGrowthOutside0X128;
    uint256 feeGrowthOutside1X128;
}

/**
 * @dev Doubly linked list entry for active liquidity heights in fixed pools
 * @dev Tracks neighboring height levels above and below a given height.
 *
 * @dev **nextHeightBelow**  The previous active height.
 * @dev **nextHeightAbove**  The next active height.
 */
struct FixedHeightMap {
    uint256 nextHeightBelow;
    uint256 nextHeightAbove;
}

/**
 * @dev Stores position-specific metadata for fixed pools
 * @dev Tracks the height ranges and fee growth checkpoints used for calculating owed fees and value.
 *
 * @dev **startHeight0**                    Start height for token0 position range.
 * @dev **endHeight0**                      End height for token0 position range.
 * @dev **startHeight1**                    Start height for token1 position range.
 * @dev **endHeight1**                      End height for token1 position range.
 * @dev **feeGrowthInside0Of0LastX128**     Last recorded fee growth inside token0 side, token0 asset.
 * @dev **feeGrowthInside1Of0LastX128**     Last recorded fee growth inside token0 side, token1 asset.
 * @dev **feeGrowthInside0Of1LastX128**     Last recorded fee growth inside token1 side, token0 asset.
 * @dev **feeGrowthInside1Of1LastX128**     Last recorded fee growth inside token1 side, token1 asset.
 */
struct FixedPositionInfo {
    uint256 startHeight0;
    uint256 endHeight0;
    uint256 startHeight1;
    uint256 endHeight1;
    uint256 feeGrowthInside0Of0LastX128;
    uint256 feeGrowthInside1Of0LastX128;
    uint256 feeGrowthInside0Of1LastX128;
    uint256 feeGrowthInside1Of1LastX128;
}

/**
 * @dev Wrapper struct for fixed liquidity withdrawals to specify withdrawal type
 * 
 * @dev **withdrawAll**  True when withdrawing all tokens.
 * @dev **params**       ABI encoded withdrawal param details.
 */
struct FixedLiquidityWithdrawalParams {
    bool withdrawAll;
    bytes params;
}

/**
 * @dev Parameters for modifying fixed pool liquidity
 * @dev Used when adding or removing liquidity from fixed pools
 *
 * @dev **amount0**                  Maximum amount of token0 to add or exact amount to remove.
 * @dev **amount1**                  Maximum amount of token1 to add or exact amount to remove.
 * @dev **addInRange0**              True if token0 should be added in range by consuming a portion of token1 deposit.
 * @dev **addInRange1**              True if token1 should be added in range by consuming a portion of token0 deposit.
 * @dev **endHeightInsertionHint0**  Height of the linked list node closest to where the token0 position is expected to end.
 * @dev **endHeightInsertionHint1**  Height of the linked list node closest to where the token1 position is expected to end.
 * @dev **maxStartHeight0**          Maximum height of token0 that a position can start at without resulting in a revert.
 * @dev **maxStartHeight1**          Maximum height of token1 that a position can start at without resulting in a revert.
 */
struct FixedLiquidityModificationParams {
    uint256 amount0;
    uint256 amount1;
    bool addInRange0;
    bool addInRange1;
    uint256 endHeightInsertionHint0;
    uint256 endHeightInsertionHint1;
    uint256 maxStartHeight0;
    uint256 maxStartHeight1;
}

/**
 * @dev Parameters for modifying fixed pool liquidity
 * @dev Used when withdrawing an entire position
 * 
 * @dev **minAmount0**  Minimum amount of token0 to remove.
 * @dev **minAmount1**  Minimum amount of token1 to remove.
 */
struct FixedLiquidityWithdrawAllParams {
    uint256 minAmount0;
    uint256 minAmount1;
}

/**
 * @dev Temporary storage for swap execution state in fixed pools.
 * 
 * @dev **swapByInput**                     True when swapping by input amount.
 * @dev **zeroForOne**                      True when swapping token0 for token1.
 * @dev **amountIn**                        Total input amount for the swap operation.
 * @dev **amountOut**                       Total output amount calculated for the swap.
 * @dev **poolFeeBPS**                      LP fee rate in basis points.
 * @dev **protocolFeeBPS**                  Protocol fee rate in basis points.
 * @dev **protocolFee**                     Absolute protocol fee amount collected.
 * @dev **lpFeeAmount**                     Total fee amount for this swap for the LP.
 * @dev **packedRatio**                     Packed ratio of token0 to token1 representing price.
 * @dev **inputShareOfExpectedReserve**     Amount of the expected reserve token attributed to the input token.
 * @dev **outputShareOfExpectedReserve**    Amount of the expected reserve token attributed to the output token.
 * @dev **expectedReserve**:                Current available reserve of the output token.
 * @dev **consumedLiquidityInputHeight**:   Amount of consumed liquidity in the input token's height.
 * @dev **consumedLiquidityOutputHeight**:  Amount of consumed liquidity in the output token's height.
 * @dev **outputHeightInputShare**:         Output height consumed liquidity's share of input reserves.
 */
struct FixedSwapCache {
    bool swapByInput;
    bool zeroForOne;
    uint256 amountIn;
    uint256 amountOut;
    uint16 poolFeeBPS;
    uint16 protocolFeeBPS;
    uint256 protocolFee;
    uint256 lpFeeAmount;
    uint256 packedRatio;
    uint256 inputShareOfExpectedReserve;
    uint256 outputShareOfExpectedReserve;
    uint256 expectedReserve;
    uint256 consumedLiquidityInputHeight;
    uint256 consumedLiquidityOutputHeight;
    uint256 outputHeightInputShare;
}

/**
 * @notice Internal cache for fixed liquidity modifications
 * @dev Used internally to avoid stack too deep errors during liquidity operations
 * 
 * @dev **startHeight0**       The start height for token0 liquidity to be added at.
 * @dev **startHeight1**       The start height for token1 liquidity to be added at.
 * @dev **endHeight0**         The end height for token0 liquidity to be added at.
 * @dev **endHeight1**         The end height for token1 liquidity to be added at.
 * @dev **amountAddedOf0To0**  The amount of token0 liquidity added to token0 reserves.
 * @dev **amountAddedOf0To1**  The amount of token1 liquidity added as in-range token0 liquidity.
 * @dev **amountAddedOf1To0**  The amount of token0 liquidity added as in-range token1 liquidity.
 * @dev **amountAddedOf1To1**  The amount of token1 liquidity added to token1 reserves.
 */
struct ModifyFixedLiquidityCache {
    uint256 startHeight0;
    uint256 startHeight1;
    uint256 endHeight0;
    uint256 endHeight1;
    uint256 amountAddedOf0To0;
    uint256 amountAddedOf0To1;
    uint256 amountAddedOf1To0;
    uint256 amountAddedOf1To1;
}